AWSTemplateFormatVersion: '2010-09-09'
Description: CFN Init Demo - Just create Metadata Template

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 128.168.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
       - Key: name
         Value: radyCloudFormationVPC
  mySubnets:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: us-east-1a
        VpcId: !Ref myVPC
        CidrBlock: 128.168.10.0/24
        MapPublicIpOnLaunch: true
        Tags:
          - Key: name
            Value: radySubnet
  mySubnets2:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: us-east-1b
        VpcId: !Ref myVPC
        CidrBlock: 128.168.20.0/24
        MapPublicIpOnLaunch: true
        Tags:
          - Key: name
            Value: radySubnet2
  myRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: name
          Value: route table for IGW
  myRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref myRouteTable
      DestinationCidrBlock: 0.0.0.0/0 
      GatewayId: !Ref myInternetGateway 
  

      
    
    